### ISSUE TITLE
(Should) Use WPF instead of WinForms

### ISSUE THREAD

**Issue by Dokman** [TechPenguineer/Hypermc#3]
It's written in XAML that is easily readable and editable.
it can be used with MVC (Model View Controller) so can be extended easily.
Apart there are a lot of libs that can make the UI better like Mahapps.Metro

**Comment by Krutonium** [comment]
I disagree - If there's a goal of making this work on Linux (Which I am totally willing to help with), WPF is an awful choice, since it outright doesn't work. WinForms does, but I'd be more inclined to suggest [ETO](https://github.com/picoe/Eto) - You can use XAML, or design your UI in code, and it'll compile to native UI's for MacOS, Linux, and Windows.

**Comment by Dokman** [comment]
> I disagree - If there's a goal of making this work on Linux (Which I am totally willing to help with), WPF is an awful choice, since it outright doesn't work. WinForms does, but I'd be more inclined to suggest [ETO](https://github.com/picoe/Eto) - You can use XAML, or design your UI in code, and it'll compile to native UI's for MacOS, Linux, and Windows.

i didn't know that library. That library is amazing.

**Comment by VoidyCD** [comment]
resolved issue.
